// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLy4QV28DeKuCBQf6Rfd2O8hZa7zWLHr0',
    appId: '1:668962093281:web:647e2e9eca34c6520bdfa0',
    messagingSenderId: '668962093281',
    projectId: 'minimal-chatting-app',
    authDomain: 'minimal-chatting-app.firebaseapp.com',
    storageBucket: 'minimal-chatting-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlvwrkM5eJt6xNWYl0Mx4bCG9-kl2Y30w',
    appId: '1:668962093281:android:a6f562cf19fed8db0bdfa0',
    messagingSenderId: '668962093281',
    projectId: 'minimal-chatting-app',
    storageBucket: 'minimal-chatting-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYO_LIvqtJcmO5j5ZXh0Q402pGLzsoPC8',
    appId: '1:668962093281:ios:41ae033afd1690400bdfa0',
    messagingSenderId: '668962093281',
    projectId: 'minimal-chatting-app',
    storageBucket: 'minimal-chatting-app.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYO_LIvqtJcmO5j5ZXh0Q402pGLzsoPC8',
    appId: '1:668962093281:ios:f74a4d8c413be4cc0bdfa0',
    messagingSenderId: '668962093281',
    projectId: 'minimal-chatting-app',
    storageBucket: 'minimal-chatting-app.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
